spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root
        url: jdbc:mysql://${ipAddr}:3306/meituan-admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        initial-size: 10
        max-active: 100
        min-idle: 10
        max-wait: 60000
        pool-prepared-statements: true
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000


##多数据源的配置
#dynamic:
#  datasource:
#    slave1:
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://localhost:1433;DatabaseName=renren_security
#      username: sa
#      password: 123456
#    slave2:
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://localhost:5432/renren_security
#      username: renren
#      password: 123456


#分布式事务Seata配置
#seata:
#    tx-service-group: ${spring.application.name}
#    enabled: true
#    enable-auto-data-source-proxy: true
#    service:
#        vgroup-mapping:
#            payment: default
#        grouplist:
#            default: 101.200.140.80:8091

