ipAddr: 101.200.140.80
spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://meituan-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        - id: member_route
          uri: lb://meituan-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        - id: auth_route
          uri: lb://meituan-authserver
          predicates:
            - Path=/api/oauth/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        - id: oauth_route
          uri: lb://meituan-authserver
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        - id: oss_route
          uri: lb://meituan-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        - id: admin_route
          uri: lb://meituan-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}


  #filters进行路径重写 需要注意的就是 精确的路由放在前面 模糊的路由放在后面 需要注意的一点就是 nginx
  #在将请求代理给 网关的时候 会将host 信息进行丢弃
  # 配置 rsa 公钥地址
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9000/rsa/publicKey'
  redis:
    host: ${ipAddr}
    password: redis123


secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/api/oauth/token"
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.jpg"
      - "/**/*.ico"
    # --- 前台首页 ---
      - "/api/product/category/listWithTree"
      - "/api/auth/registerUser"
      - "/api/thirdparty/msm/send/**"
      - "/api/auth/*/Callback"
